# Generated by Django 5.0 on 2024-02-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('BB', 'Banco do Brasil'), ('CE', 'Caixa Econômica'), ('NU', 'Nubank')], max_length=2),
        ),
    ]
