# Generated by Django 5.0 on 2024-02-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagar',
            old_name='data_pagamento',
            new_name='dia_pagamento',
        ),
    ]
